### ISSUE TITLE
Chauchera no se está sincronizando. 

### ISSUE THREAD

**Issue by FeroSalgado** [proyecto-chaucha/chauchera#11]
Estimados,  chauchera no se está sincronizando, favor revisar el tema con urgencia.

**Comment by FeroSalgado** [comment]
El log de chauchera entrega muchos "connection timeout"

**Comment by FeroSalgado** [comment]
Chauchera sincronizó después de unas muchos intentos ... ^^

**Comment by clsource** [comment]
Se viene la versión 0.13 👍

**Comment by buskerone** [comment]
v1.0.0 macos "sincronizando con la red" x horas

**Comment by clsource** [comment]
Will be fixed in new version 👍

**Comment by buskerone** [comment]
cool, thx!
