### ISSUE TITLE
CDB(): can't open database file wallet.dat, error -30974

### ISSUE THREAD

**Issue by fixmycode** [proyecto-chaucha/chauchera#2]
The app won't open in OS X 10.11.6, after bypassing the unidentified developer application warning and shows this error, which can't be seen, as it appears behind the splashscreen.

![screen shot 2017-12-09 at 20 47 28](https://user-images.githubusercontent.com/705903/33800652-f755b230-dd22-11e7-87b8-dc9f5a0d11cf.png)

**Comment by clsource** [comment]
Hello, Thanks for Reporting.
It´s seems the problem it's in the compilation.
The chauchera binary was compiled in MacOS 10.12.6 so maybe some weird tricks should be made in order to be compatible with older systems. (Like compiling on OSX Lion).

I will look into it, maybe using a VM.
