### ISSUE TITLE
./chaucha-qt: error while loading shared libraries: libminiupnpc.so.8

### ISSUE THREAD

**Issue by fixmycode** [proyecto-chaucha/chauchera#4]
In Ubuntu 17.10, there's an error:

    ./chaucha-qt: error while loading shared libraries: libminiupnpc.so.8: cannot open shared object file: No such file or directory

the `libboost-all-dev` package version is 1.62.0.1

**Comment by sebaswind** [comment]
I was able to bypass this by creating a symlink of the newer version.
`ln -s /usr/lib/x86_64-linux-gnu/libminiupnpc.so.10 /usr/lib/x86_64-linux-gnu/libminiupnpc.so.8`
this seems to work with almost all unmet requirements, but it fails with openssl version.

**Comment by Z-WolF** [comment]
I also made simlinks for every "not found":

```$ ldd ./chaucha-qt
	libminiupnpc.so.8 => not found
	libboost_system.so.1.54.0 => not found
	libboost_filesystem.so.1.54.0 => not found
	libboost_program_options.so.1.54.0 => not found
	libboost_thread.so.1.54.0 => not found```

In the end i got a "Segmentation Fault" error.

**Comment by sapienman** [comment]
The same problem here :c

**Comment by clsource** [comment]
thanks for reporting.
Will have this issue in the backlog.
👍

**Comment by clsource** [comment]
at the moment is better to use wine.
updating to litecoin 0.13 in progress

**Comment by on1link** [comment]
There's an update for this issue?

**Comment by fixmycode** [comment]
with Cauchera being replaced by Chauchera-new next week, I don't think this
is going to be fixed.

On Jan 8, 2018 22:28, "on1link" <notifications@github.com> wrote:

There's an update for this issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/proyecto-chaucha/chauchera/issues/4#issuecomment-356150893>,
or mute the thread

**Comment by clsource** [comment]
Actually most bugs reported here would be fixed with the new chauchera

**Comment by alexorbit** [comment]
sudo apt-get install libminiupnpc-dev
