### ISSUE TITLE
Error al compilar desde Qt-Creator.

### ISSUE THREAD

**Issue by MRcthulu** [proyecto-chaucha/chauchera#6]
chauchera-1.0.2-e1c76a9d0b877988395ae4fcf832c66dbb93f104/src/bignum.h:51: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~

**Comment by clsource** [comment]
gracias
estamos actualizando a litecoin 0.13.
esperamos que se puedan arreglar la mayor parte de estos issues 👍
