### ISSUE TITLE
Chauchera incompatible con MacOSX 10.11.6

### ISSUE THREAD

**Issue by sebastianfelipe** [proyecto-chaucha/chauchera#7]
Estimados,

Acabo de instalar el cliente y tira error de incompatibilidad :/

**Comment by clsource** [comment]
Si, se debe compilar en una versión anterior de Mac para asegurar compatibilidad con versiones recientes.

Estamos trabajando en eso :)

Muchas gracias por reportar 👍

**Comment by Chauchito** [comment]
Hola! En cuanto tiempo más este error estará resuelto? 
Saludos!

**Comment by clsource** [comment]
En las primeras semanas de enero.
Se está creando un roadmap más explícíto del proyecto para más transparencia

**Comment by nkittsteiner** [comment]
A mi me anda bien el chaucha-qt_1.0.0-macos.zip en Mac 10.13.1

**Comment by clsource** [comment]
lo ideal es igual tratar de tener la última versión de mac.
ojala de la 10.12 hacia arriba (no mas de 2 años de antiguedad)
