### ISSUE TITLE
No puedo satisfacer todas las dependencias en linux

### ISSUE THREAD

**Issue by WHK102** [proyecto-chaucha/chauchera#8]
No todas las dependencias recomendadas para la ejecución del binario en linux funcionan, hacen falta aun mas librerías, por ejemplo:

```
whk@machine:~/chaucha-qt_1.0.0-linux$ ./chaucha-qt 
./chaucha-qt: error while loading shared libraries: libminiupnpc.so.8: cannot open shared object file: No such file or directory
```
Lo resolví siguiendo el consejo desde https://github.com/bitconnectcoin/bitconnectcoin/issues/3 :
`sudo su && cd /usr/lib/x86_64-linux-gnu && ln -s libminiupnpc.so.10 libminiupnpc.so.8 && ldconfig -v`

Ahora me falta el archivo libboost_system.so.1.54.0 asi que hice algo similar y le hice un enlace simbólico desde la versión 1.58.0 y funcionó pero ahora me pide otro: libboost_filesystem.so.1.54.0, asi que definitivamente no voy a estar toda la tarde renombrando librerías ya que entendí que la chauchera exige una versión determinada de la librería libboost que no utiliza ubuntu 16.04 en los repositorios estables, en su reemplazo hace uso de la versión 1.58.

Buscaré alguna manera para hacer un downgrade para hacer funcionar la chauchera, pero de todas maneras podrían darle soporte a las versiones mas actuales estables de sus dependencias.

**Comment by clsource** [comment]
hola gracias.
estamos actualizando a la version 0.13 lo que arreglará muchas dependencias.
por mientras recomendamos usar wine 👍
