### ISSUE TITLE
Faltan instrucciones para su compilación en linux

### ISSUE THREAD

**Issue by WHK102** [proyecto-chaucha/chauchera#9]
Donde están las instrucciones para compilar en linux? falta el archivo makefile que debiera estar incluido como cualquier proyecto, el único readme para compilación es para window$ lovers.

**Comment by klud1** [comment]
Me sumo a esto; además, trato de ejecutar `chaucha-qt` y aparecen varios errores que he tratado de resolver creando symlinks, todo parece funcionar, pero al final arroja un segmentation fault

```sh
$ ./chaucha-qt
./chaucha-qt: error while loading shared libraries: libminiupnpc.so.8: cannot open shared object file: No such file or directory

$ sudo ln -s /usr/lib64/libminiupnpc.so.16 /usr/lib64/libminiupnpc.so.8

$ ./chaucha-qt
./chaucha-qt: error while loading shared libraries: libboost_system.so.1.54.0: cannot open shared object file: No such file or directory

 $ sudo ln -s /usr/lib64/libboost_system.so /usr/lib64/libboost_system.so.1.54.0 

$ ./chaucha-qt
./chaucha-qt: error while loading shared libraries: libboost_system.so.1.54.0: cannot open shared object file: No such file or directory

$ ./chaucha-qt
./chaucha-qt: error while loading shared libraries: libboost_system.so.1.54.0: cannot open shared object file: No such file or directory

$ sudo ln -sfv /usr/lib64/libboost_system.so.1.65.1 /usr/lib64/libboost_system.so.1.54.0 
'/usr/lib64/libboost_system.so.1.54.0' -> '/usr/lib64/libboost_system.so.1.65.1'

$ ./chaucha-qt
./chaucha-qt: error while loading shared libraries: libboost_filesystem.so.1.54.0: cannot open shared object file: No such file or directory

$ sudo ln -sfv /usr/lib64/libboost_system.so.1.65.1 /usr/lib64/libboost_system.so.1.54.0
'/usr/lib64/libboost_system.so.1.54.0' -> '/usr/lib64/libboost_system.so.1.65.1'

$ ./chaucha-qt
./chaucha-qt: error while loading shared libraries: libboost_filesystem.so.1.54.0: cannot open shared object file: No such file or directory

$ sudo ln -sfv /usr/lib64/libboost_filesystem.so.1.65.1 /usr/lib64/libboost_filesystem.so.1.54.0
'/usr/lib64/libboost_filesystem.so.1.54.0' -> '/usr/lib64/libboost_filesystem.so.1.65.1'

$ ./chaucha-qt
./chaucha-qt: error while loading shared libraries: libboost_program_options.so.1.54.0: cannot open shared object file: No such file or directory

$ sudo ln -sfv /usr/lib64/libboost_program_options.so.1.65.1 /usr/lib64/libboost_program_options.1.54.0
'/usr/lib64/libboost_program_options.1.54.0' -> '/usr/lib64/libboost_program_options.so.1.65.1'

$ ./chaucha-qt
./chaucha-qt: error while loading shared libraries: libboost_program_options.so.1.54.0: cannot open shared object file: No such file or directory

$ sudo ln -sfv /usr/lib64/libboost_program_options.so.1.65.1 /usr/lib64/libboost_program_options.so.1.54.0
'/usr/lib64/libboost_program_options.so.1.54.0' -> '/usr/lib64/libboost_program_options.so.1.65.1'

$ ./chaucha-qt
./chaucha-qt: error while loading shared libraries: libboost_thread.so.1.54.0: cannot open shared object file: No such file or directory

$ sudo ln -sfv /usr/lib64/libboost_thread.so.1.65.1 /usr/lib64/libboost_thread.so.1.54.0
'/usr/lib64/libboost_thread.so.1.54.0' -> '/usr/lib64/libboost_thread.so.1.65.1'

$ ./chaucha-qt

(chaucha-qt:4218): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(chaucha-qt:4218): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",

(chaucha-qt:4218): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",
[1]    4218 segmentation fault (core dumped)  ./chaucha-qt
```

Una guía para compilarlo en linux estaría genial.

**Comment by clsource** [comment]
Los principales problemas son por que las dependencias igual son un poco viejitas.
recomiendo por mientras actualizamos a 0.13 usar wine.

**Comment by WHK102** [comment]
Ni loco voy a instalar casi 1gb de wine ensuciando mi sistema operativo o virtualizando y comprando una lisencia de window$ por casi 150USD solo para hacer correr la chauchera, me va a salir mas caro el windows que lo que pueda ganar en chauchas xD, definitivamente las chauchas no estan pensadas para ser usadas desde otro sistema que no sea un windows o para gente que no tenga window$ como costo hundido. Le faltó preparación a las chauchas antes de haberlo sacado a público.

**Comment by clsource** [comment]
la chauchera corre en linux sin problemas, la version de wine es un parche para quien quiera una solución rápida.

debes esperar a la versión 0.13 que facilitará la pega en dependencias.

**Comment by eplazai** [comment]
yo las empece' a arreglar creando los symlinks

Vi donde estaba la version del libboost con: locate libboost_system

...y luego cree los symlinks

i.e.: ln -s /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0 /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0

Hice lo mismo con cada uno de los que me faltaban. El problema es que al final obtengo un Segmentation Fault. 

PS: En macOS tampoco corre.

**Comment by waflessnet** [comment]
para compiltar con qt5 tienen que instalar qmake, las dependecias en estan en el readme doc/readme-qt.rst
![image](https://user-images.githubusercontent.com/6413704/34385992-2640e200-eb05-11e7-93d0-34105a2f301a.png)

lo que no esta en la documentación es que deben hacer en la raíz del proyecto :

> $ qmake chaucha-qt.pro 


esto creara un archivo makefile , entonces corren  make :
> $ make 


![image](https://user-images.githubusercontent.com/6413704/34386069-9d5ba67c-eb05-11e7-908e-bcf6309b0cd3.png)
